"""
Central configuration for Bishop AI Research Agent.
Edit these lists to tune what the agent monitors and how sensitive it is.
"""

REDDIT_SUBREDDITS = [
'artificial',
'AIAutomation',
'n8n',
'zapier',
'automation',
'nocode',
'lowcode',
'ChatGPT',
'PromptEngineering',
'AutoGPT',
'LangChain',
'LocalLLaMA',
'ClaudeAI',
'OpenAI',
'AIAssistants',
'mcp',
'ArtificialIntelligence',
'MachineLearning',
'GPT4',
'perplexity_ai',
'entrepreneur',
'Entrepreneur',
'smallbusiness',
'startups',
'SaaS',
'agency',
'consulting',
'business',
'EntrepreneurRideAlong',
'microsaas',
'Bootstrapped',
'growmybusiness',
'sweatystartup',
'passive_income',
'marketing',
'DigitalMarketing',
'PPC',
'SEO',
'sales',
'socialmedia',
'content_marketing',
'copywriting',
'customerservice',
'CustomerSuccess',
'Operations',
'emailmarketing',
'leadgeneration',
'growthhacking',
'ecommerce',
'FulfillmentByAmazon',
'Shopify',
'realtors',
'legaltech',
'Accounting',
'Bookkeeping',
'humanresources',
'projectmanagement',
'recruiting',
'forhire',
'hiring',
'WorkOnline',
'freelance',
'digitalnomad',
'VirtualAssistants',
'webdev',
'freelancing',
'productivity',
'Notion',
'MakeApp',
'hubspot',
'salesforce',
'airtable',
]

REDDIT_KEYWORDS = [
'AI automation',
'automate with AI',
'AI workflow',
'need help automating',
'looking for AI',
'hire AI',
'AI agency',
'AI consultant',
'AI freelancer',
'automate my business',
'AI implementation',
'need someone to build',
'looking to hire',
'recommend an AI',
'AI expert for hire',
'AI developer for hire',
'AI specialist needed',
'looking for automation expert',
'hire n8n developer',
'hire automation specialist',
'workflow automation',
'business automation',
'ChatGPT automation',
'GPT workflow',
'n8n help',
'zapier alternative',
'Make automation',
'GoHighLevel AI',
'HubSpot automation',
'AI for CRM',
'AI agent for my business',
'build me an AI',
'Claude API',
'OpenAI API help',
'build with Claude',
'AI for my business',
'AI tools recommendation',
'automate repetitive',
'save time with AI',
'AI strategy',
'AI chatbot for business',
'AI for customer service',
'AI for marketing',
'AI for sales',
'AI for operations',
'drowning in manual',
'too much manual work',
'overwhelmed with tasks',
'need to scale',
'wasting hours',
'manual process',
'repetitive tasks',
'learn AI automation',
'AI training',
'AI course',
'AI workshop',
'implement AI',
'AI onboarding',
'teach my team AI',
'AI for my team',
'where do I start with AI',
'getting started with AI',
'AI bootcamp',
'AI coaching',
'learn to use AI',
'AI education',
'understand AI for business',
'prompt engineering',
'better prompts',
'ChatGPT not working',
'AI giving bad results',
'how to prompt',
'prompt help',
'ChatGPT useless',
'AI outputs are bad',
'get better results from AI',
'prompt template',
'AI not understanding me',
'ChatGPT keeps getting it wrong',
'Claude not giving',
'Gemini not helpful',
'AI prompt tips',
'write better prompts',
'prompt writing',
'improve my prompts',
]

REDDIT_POST_LIMIT = 25
REDDIT_POLL_INTERVAL_MINUTES = 15